### ISSUE TITLE
runtime-perm.md initApp() before Permissions Granted

### ISSUE THREAD

**Issue by SilentServices** [wajahatkarim3/Today-I-Learned#3]
Hi,

first of all: Thank you very much for your lessions and the effort you put into this. Much appreceated!

I found an issue in you runtime permissions writeup. In the onRequestPermissionsResult callback you are just checking if permissions are denied and if not initApp() is called. This bypasses the logic that the initApp() should only be called if permissions are granted. I have solved this by changing it to the following:

```
            int deniedCount = 0;
            int grantedCount = 0;

            // Gather permission grant results
            for (int i=0; i<grantResults.length; i++)
            {
                // Add only permissions which are denied
                if (grantResults[i] == PackageManager.PERMISSION_DENIED)
                {

                    permissionResults.put(permissions[i], grantResults[i]);
                    deniedCount++;
                }
                if (grantResults[i] == PackageManager.PERMISSION_GRANTED)
                {

                    permissionResults.put(permissions[i], grantResults[i]);
                    grantedCount++;
                }
            }

            // Check if all permissions are granted
            if (deniedCount == 0 && grantedCount != 0)
```

**Comment by wajahatkarim3** [comment]
Thank you for your findings. I am a little confused here in your code. If we add all the granted permissions results in {{permissionResults}} map, then how can we differentiate on which permissions are granted and which are denied. You see, I am later asking only those permissions which are in the `permissionResults` map, that's why I have only added denied check. 

Another reason for this is that this logic is inside `onRequestPermissionsResult()`. This method is only called when there're any permissions remaining and being asked and user have either accepted or denied. So, the `grantedCount` will not be the exact here. 

Anyway, if that code works for you. That's great. I will look into it today or tomorrow and add some permissions and run some checks 

Thanks again for your support. Much appreciated. 😄

**Comment by SilentServices** [comment]
Yes, you are absolutly right. My (copy/paste) fault. It should look like this:
```
int deniedCount = 0;
            int grantedCount = 0;

            // Gather permission grant results
            for (int i=0; i<grantResults.length; i++)
            {
                // Add only permissions which are denied
                if (grantResults[i] == PackageManager.PERMISSION_DENIED)
                {

                    permissionResults.put(permissions[i], grantResults[i]);
                    deniedCount++;
                }
                if (grantResults[i] == PackageManager.PERMISSION_GRANTED)
                {
                    grantedCount++;
                }
            }

            // Check if all permissions are granted
            if (deniedCount == 0 && grantedCount != 0)
```
A better solution would IMHO be to check the permission string array size and use that before calling the initApp(). I hope that makes more sense?
Cheers, Michael

**Comment by wajahatkarim3** [comment]
Totally agree with you 👍 This looks better and reliable approach. Thank you, Michael, for sharing this 😄
